### PR TITLE
Initial pull request

### PR DESCRIPTION
**Pull request by mrodozov**
needed for https://github.com/cms-sw/cmssw/pull/29284

### CODE REVIEW

**Comment by smuzaffar** [comment]
Do we need all these 0 size txt files?

**Comment by davidlange6** [comment]
gzipping would do wonders here.

**Comment by davidlange6** [comment]
well thinking more broadly - gzipping text files full of numbers should probably be required. it helps also on read back

**Comment by mrodozov** [comment]
Empty files removed. Any suggestion on how to archive the files ? maybe from external data repo ?

**Comment by skinnari** [comment]
please close this PR, I will put in a modified one that takes out the scripts not needed for production as well as with updated LUTs, thanks.

**Comment by skinnari** [comment]
I don't understand the cmsbuild github magic, but again (see above), please do not merge this one... i'm putting in a modified one for the L1Trigger/TrackFindingTracklet package...

**Comment by smuzaffar** [comment]
ok closing it now.

**Pull request closed without merging**
