### PR TITLE
Combined module wiring

### PR DESCRIPTION
**Pull request by aehart**
This PR introduces preliminary wiring files for the extended L1 tracking emulation with combined modules.

In particular, the TrackletProcessorDisplaced (TPD_\*) replaces the TrackletEngineDisplaced (TED_\*), TripletEngine (TRE_\*), and TrackletCalculatorDisplaced (TPD_\*). This configuration is not currently the default for the extended tracking, but is under development and will be needed for the eventual firmware to meet latency requirements.

@tomalin @skinnari @gershtein

### CODE REVIEW

**Comment by epalencia** [comment]
Please test

**Comment by smuzaffar** [comment]
@aehart , all these are new data files. Is there any cmssw PR use these?

**Comment by tomalin** [comment]
> @aehart , all these are new data files. Is there any cmssw PR use these?

We hope to make a cmssw PR today.

**Comment by cecilecaillol** [comment]
+l1

**Comment by rappoccio** [comment]
+1

* Extensive review in https://github.com/cms-sw/cmssw/pull/38341, this looks like it converged.

**Comment by tomalin** [comment]
Dear all, this PR has been waiting for 5 months for no apparent reason. It is needed by the L1 tracking code. Can we merge it?

**Comment by perrotta** [comment]
please test
(last ones were quite some time ago)

**Comment by perrotta** [comment]
+1

**Comment by perrotta** [comment]
merge

**Pull request merged**
