### PR TITLE
Update data-files (match cms-sw PR #34028)

### PR DESCRIPTION
**Pull request by skinnari**
**UPDATE: This should be coupled with fixed CMSSW PR #34028 rather than the earlier mentioned**

This PR must be coupled with cms-sw PR #34028 (update of L1 tracking algorithm) and should be merged and go in to the same release. 

- Removes files that become unused with code updates in PR #34028
- Updated configuration files for the extended (displaced) tracking to work with new InputRouter module

=> Please only merge when PR #34028 (https://github.com/cms-sw/cmssw/pull/34028) gets included!

### CODE REVIEW

**Comment by cecilecaillol** [comment]
please test

**Comment by cecilecaillol** [comment]
+l1

**Comment by skinnari** [comment]
This fails because it is tested without https://github.com/cms-sw/cmssw/pull/34028

**Comment by mrodozov** [comment]
please test with cms-sw/cmssw#34028

**Comment by mrodozov** [comment]
this should go together with 34028 then

**Comment by skinnari** [comment]
exactly, as mentioned in the description: "Please only merge when PR #34028 (cms-sw/cmssw#34028) gets included" 

cms-sw/cmssw#34028 is already being tested with this cms-data PR. thanks!

**Comment by mrodozov** [comment]
+externals
the release manager will get it in with the cmssw pr

**Comment by qliphy** [comment]
+1

**Pull request merged**
