### PR TITLE
Extended wiring with all combined modules

### PR DESCRIPTION
**Pull request by aehart**
This PR adds a new wiring for the "extended" (i.e., prompt + displaced) tracking. The wiring uses the newer "combined" processing modules consistently, which is not the case for the existing wirings.

Once this is merged, we plan to make this the default wiring for extended tracking in https://github.com/cms-sw/cmssw/pull/45974.

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by tomalin** [comment]
> This PR adds a new wiring for the "extended" (i.e., prompt + displaced) tracking. The wiring uses the newer "combined" processing modules consistently, which is not the case for the existing wirings.
> 
> Once this is merged, we plan to make this the default wiring for extended tracking in [cms-sw/cmssw#45974](https://github.com/cms-sw/cmssw/pull/45974).

N.B. This means that this updat to cms-data and PR45974 must be introduced into the same version of CMSSW.

**Comment by tomalin** [comment]
> This PR adds a new wiring for the "extended" (i.e., prompt + displaced) tracking. The wiring uses the newer "combined" processing modules consistently, which is not the case for the existing wirings.
> 
> Once this is merged, we plan to make this the default wiring for extended tracking in [cms-sw/cmssw#45974](https://github.com/cms-sw/cmssw/pull/45974).

This PR to cms-data should go into the same CMSSW release as https://github.com/cms-sw/cmssw/pull/46360 , as they depend on each other. (PR46360 has replaced PR45974, which has been closed).

**Comment by mandrenguyen** [comment]
+1

**Comment by mandrenguyen** [comment]
merge
Assuming L1 sig, since they signed the PR which relies on this PR

**Pull request merged**
