### PR TITLE
data files for L1 tracking (hybrid algorithm, tracklet part)

### PR DESCRIPTION
**Pull request by skinnari**
This is to include data files needed for the L1 tracking. The corresponding PR of code to cms-sw is here: 

https://github.com/cms-sw/cmssw/pull/29527

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
please test

**Comment by smuzaffar** [comment]
@skinnari , we still have many 0 size files in the PR. Do we want to keep these empty files?

**Comment by skinnari** [comment]
> @skinnari , we still have many 0 size files in the PR. Do we want to keep these empty files?

@smuzaffar yes, the experts (@aehart) have specified that it is on the to-do list to ultimately simplify these files, but empty lines have a meaning for these look-up tables and they are needed in their current state.

**Pull request merged**
